#!/usr/bin/env bash

set -Eeu -o pipefail

die_if_dirty() {
    git_status=$(git status -s)
    if [[ $git_status ]]; then
        die "commit or stash files before switch\n$git_status"
    fi
}

die() { echo -e "!! $*"; exit 1; }

die_if_dirty
git checkout nixos-25.05
git pull
git rebase nixos-25.05 my-nixos-25.05
